### ISSUE TITLE
Install instructions: Iris not in scitools repository anymore

### ISSUE THREAD

**Issue by childen** [wegener-center/pyCAT#3]
The iris dependencies do not seem to be in the scitools conda repositiory anymore. For us using the conda-forge repository instead worked well:

``conda config --add channels conda-forge``

**Comment by dragonburn1991** [comment]
There is an error in method.py at line 62 'and obs_cube.data.mask[index]:' which 'mask' is a boolean value while the code was trying to index the 'mask' which cause an error.
Please have a look and give me some advice 
Additionally, I could not successfully run the example code in the manual
