### ISSUE TITLE
the code is trying to index boolean value

### ISSUE THREAD

**Issue by dragonburn1991** [wegener-center/pyCAT#4]
There is an error in method.py at line 62 'and obs_cube.data.mask[index]:' which 'mask' is a boolean value while the code is trying to index the 'mask' which cause an error.
Please have a look and give me some advice
Additionally, I could not successfully run the example code in the manual

**Comment by mir06** [comment]
Thank you for pointing this out. This is due to a change in iris 2.X. I will provide a corrected version.
