### ISSUE TITLE
sample-data model*.nc  

### ISSUE THREAD

**Issue by peteradeg** [wegener-center/pyCAT#5]
I've installed anaconda and files in setup.py. 

NB I downgraded iris to 2.2.1  because with the standard version I got a conflict see https://github.com/cedadev/jasmin_scivm/issues/154

-- python version 3.7.3
-- iris version 2.2.1dev0

Issues with sample data in docs (maybe the iris version is problem?) 

I note that when using: 
from netCDF4 import Dataset, I have no problems with the data.

I also note from the output below it is mysterious why line7  qm.correct() throws an error on line 178 in pycat/esd/__init__.py. Because line 178 is in the class Bias corrector whereelse line 7 qm.correct() is referencing the class definined on line 236.

many thnaks

Output below.
----

from pycat.io import Dataset
from pycat.esd import QuantileMapping
obs = Dataset('sample-data', 'observation.nc')
mod = Dataset('sample-data', 'model*.nc')
sce = Dataset('sample-data', 'scenario*.nc')
qm = QuantileMapping(obs, mod, sce)
qm.correct()

----

ValueError                                Traceback (most recent call last)
<ipython-input-2-4d35b1794978> in <module>
      5 sce = Dataset('sample-data', 'scenario*.nc')
      6 qm = QuantileMapping(obs, mod, sce)
----> 7 qm.correct()

/mnt/y/Development/conda/pyCAT-master/pycat/esd/__init__.py in correct(self, unit_list, *args, **kwargs)
    176             # extract data from obs, mod and sce
    177             obs_cube = obs_cube or self.obs.get_cube(window_constraint)
--> 178             mod_cube = self.mod.get_cube(window_constraint)
    179 
    180             regridder = regridder or self.interpolator.regridder(

/mnt/y/Development/conda/pyCAT-master/pycat/io/__init__.py in get_cube(self, extra_constraints)
    172 
    173         if self.extent != self._orig_extent:
--> 174             constraints &= self._extent_constraint()
    175 
    176         with iris.FUTURE.context(cell_datetime_objects=True):

/mnt/y/Development/conda/pyCAT-master/pycat/io/__init__.py in _extent_constraint(self)
    225 
    226         inside_indices = np.where(mask)
--> 227         minx, maxx = inside_indices[xdim].min(), inside_indices[xdim].max()
    228         miny, maxy = inside_indices[ydim].min(), inside_indices[ydim].max()
    229 

~/miniconda3/envs/iris/lib/python3.7/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims, initial, where)
     32 def _amin(a, axis=None, out=None, keepdims=False,
     33           initial=_NoValue, where=True):
---> 34     return umr_minimum(a, axis, None, out, keepdims, initial, where)
     35 
     36 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by mir06** [comment]
Thank you for reporting this bug.

`pyCAT` was tested with python3.4 (which is not maintained anymore) and python2.7 (with end-of-life on 2020-01-01).

 - [x] upgrade `pyCAT` to python3.7

**Comment by mir06** [comment]
There is a projection problem when using `proj4 = 6.1.1`. The coordinates are not unrotated correctly and thus there is no geographical overlapping between observation and model data.

I will create an issue at https://github.com/OSGeo/PROJ

For now just try to downgrade `proj4` in your conda environment:
```shell
conda install proj4=6.1.0
```
and try the sample test again.

Anyway the case of not matching observation and model region has to be caught and treated in a better way.

**Comment by mir06** [comment]
There is already an issue (OSGeo/PROJ#1601) solved with merge request. So it's just a matter of time when it will be released.
