### ISSUE TITLE
How to solve pyCAT code such as` conda install --file conda-requirements.txt shows ailed with initial frozen solve and failed with repodata from current_repodata.json,

### ISSUE THREAD

**Issue by pradhancda** [wegener-center/pyCAT#6]
(pycat) C:\Users\ANMOL>conda install --file conda-requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining python=3.8:  14%|████████▊                                                     | 1/7 [00:08<00:50,  8.48s/it]|failed                                                      /                                                        /

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package mkl_random conflicts for:
statsmodels -> numpy[version='>=1.15.4,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0|>=1.0.4,<2.0a0']
iris -> numpy[version='>=1.14,!=1.15.2'] -> mkl_random[version='>=1.0.2,<2.0a0|>=1.0.4,<2.0a0']

Package vs2015_runtime conflicts for:
statsmodels -> vc[version='>=14,<15.0a0'] -> vs2015_runtime[version='>=14.0.25123,<15.0a0|>=14.0.25420|>=14.15.26706|>=14.16.27012']
statsmodels -> vs2015_runtime[version='>=14.16.27012,<15.0a0']

Package setuptools conflicts for:
sphinx -> setuptools
python=3.8 -> pip -> setuptools
iris -> matplotlib-base -> setuptools
nose -> setuptools
setuptools

Package sqlite conflicts for:
sphinx -> python[version='>=3.5'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.30.0,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0']
nose -> python[version='>=3.8,<3.9.0a0'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0']
proj4==6.1.0 -> sqlite[version='>=3.26.0,<4.0a0']
iris -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0']
python=3.8 -> sqlite[version='>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0']
statsmodels -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0']
setuptools -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0']

Package packaging conflicts for:
sphinx -> packaging
python=3.8 -> pip -> packaging

Package certifi conflicts for:
setuptools -> certifi[version='>=2016.09|>=2016.9.26']
sphinx -> requests[version='>=2.5.0'] -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
nose -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']

Package python_abi conflicts for:
setuptools -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp37m|*_cp36m|*_cp38']
nose -> python_abi[version='2.7.*|3.7.*|3.8.*|3.6.*',build='*_cp37m|*_cp38|*_cp27m|*_cp36m']
statsmodels -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp37m|*_cp36m|*_cp38']
iris -> cartopy[version='>=0.14'] -> python_abi[version='2.7.*|3.6.*|3.7.*|3.8.*',build='*_cp27m|*_cp37m|*_cp38|*_cp36m']
setuptools -> certifi[version='>=2016.9.26'] -> python_abi=2.7[build=*_cp27m]
sphinx -> docutils[version='>=0.12'] -> python_abi[version='2.7.*|3.6.*|3.8.*|3.7.*',build='*_cp37m|*_cp27m|*_cp36m|*_cp38']

Package pyparsing conflicts for:
iris -> matplotlib-base -> pyparsing
sphinx -> packaging -> pyparsing[version='>=2.0.2']

Package nose conflicts for:
nose
iris -> cartopy[version='>=0.14'] -> nose

Package vc conflicts for:
statsmodels -> vc[version='14.*|9.*|>=14,<15.0a0|>=14.1,<15.0a0']
statsmodels -> python[version='>=2.7,<2.8.0a0'] -> vc[version='10.*|>=9,<10.0a0']

Package proj4 conflicts for:
iris -> cartopy[version='>=0.14'] -> proj4[version='4.9.3|5.2.0.*|>=5.2.0,<5.2.1.0a0|>=4.9.3,<4.9.4.0a0|>=5.1.0,<5.1.1.0a0']
proj4==6.1.0

Package pytz conflicts for:
statsmodels -> pandas[version='>=0.21'] -> pytz[version='>=2017.2']
iris -> matplotlib-base -> pytz
sphinx -> babel[version='>=1.3,!=2.0'] -> pytz

Package numpy conflicts for:
statsmodels -> numpy[version='1.10.*|1.11.*|>=1.11|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16.5,<2.0a0|>=1.18.1,<2.0a0|>=1.17.5,<2.0a0|>=1.11.3,<2.0a0']
statsmodels -> pandas[version='>=0.21'] -> numpy[version='1.12.*|1.13.*|>=1.11.*|>=1.12.1,<2.0a0|>=1.9.*|>=1.13.3,<2.0a0|>=1.11.3,<1.12.0a0|>=1.4.0|>=1.15.1,<2.0a0|>=1.9|>=1.8|>=1.7']

**Comment by mir06** [comment]
Use python 3.7 as described in the [installation guide](../blob/master/INSTALL.rst)!
