### ISSUE TITLE
How to solve Iris Deprecation in pyCAT?

### ISSUE THREAD

**Issue by pradhancda** [wegener-center/pyCAT#7]
Sir,

During the run of the example code of pyCAT, the following error message is coming repeatedly. 

Error message -
" C:\miniconda3\envs\pycat2\lib\site-packages\iris\__init__.py:249: IrisDeprecation: setting the 'Future' property 'cell_datetime_objects' is deprecated and will be removed in a future release. Please remove code that sets this property.
  warn_deprecated(msg.format(name))."

regards,
Subhasis

**Comment by mir06** [comment]
This is just a deprecation warning, do not worry, I will update pyCAT soon.

**Comment by pradhancda** [comment]
Dear Sir, 

Is it possible to resolve the deprecate error shortly ???
I will be happy if you can update the pyCAT deprecate error shortly. As I am waiting for this analysis.

regards,
Subhasis Pradhan

**Comment by rwbodman** [comment]
Has there been any update to fix this?  I am running pycat in a Jupyter notebook and these warning are a nuisance, pages of the same warning message.

Kind regards,
Roger Bodman

**Comment by rwbodman** [comment]
A possible work around:
(with correct indentation)
with warnings.catch_warnings():
<BLOCKQUOTE>warnings.simplefilter("ignore")<BR>
  qm.correct()</BLOCKQUOTE>

**Comment by mir06** [comment]
Sorry that i took so long for just a few lines of code.
