### ISSUE TITLE
No netcdf outputs produced from running the test

### ISSUE THREAD

**Issue by jatin-kala** [wegener-center/pyCAT#9]
Hi,
I installed pycat and ran the test case, but no outputs have been produced in the directory that i ran the script.

What i ran:

`from pycat.io import Dataset
from pycat.esd import QuantileMapping

obs = Dataset('sample-data', 'observation.nc')
mod = Dataset('sample-data', 'model*.nc')
sce = Dataset('sample-data', 'scenario*.nc')

qm = QuantileMapping(obs, mod, sce)
qm.correct()
print("Finished running")`

It produced some warnings, and printed the "Finished running", but there are no netcdf outputs in the directory.
the log file:

`/data/Jatin/miniconda3/envs/pycat/lib/python3.7/site-packages/iris/__init__.py:249: IrisDeprecation: setting the 'Future' property 'cell_datetime_objects' is deprecated and will be removed in a future release. Please remove code that sets this property.
  warn_deprecated(msg.format(name))
Finished running`

**Comment by jatin-kala** [comment]
Ok, i found out where the files are. Turns out tempdir on my Linux box defaults to /tmp, and the output files are there. 
>>> from tempfile import gettempdir
>>> work_dir=gettempdir()
>>> print(work_dir)
/tmp

$ ls /tmp/*.nc
/tmp/quantile_mapping_tas_scenario-0_2021-2030_day-000.nc
.......

Is there an option to specify a user output path?

**Comment by mir06** [comment]
Hi @jatin-kala sorry for the late reply but you found it by yourself :smile: 

Yes you can give the `work_dir` at the creation of the Corrector object, e.g.
```
qm = QuantileMapping(obs, mod, sce, work_dir="/home/user/qm-out")
```
Be sure that the directory `/home/user/qm-out` exists and is writeable by the user running pycat.
